# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'w4-onban' do
  # Comment the next line if you don't want to use dynamic frameworks use_frameworks! 
  pod 'Toaster', '~> 2.3'
  # Pods for w4-onban
end
